# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'TeamOn' do
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    # Add any other subspecs you want to use in your project
  ]
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TeamOn

  target 'TeamOnTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TeamOn-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TeamOn-tvOS

  target 'TeamOn-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
