const images = {
  logo: require('./teamon.png'),
  search: require('./search.png'),
  fb: require('./facebook.png'),
  twitter: require('./twitter.png'),
  instagram: require('./instagram.png'),
  linkedin: require('./linkedin.png'),
  skype: require('./skype.png'),
  avatar: require('./no-avatar.png'),
  avatarAdd: require('./addUser.png'),
  nmma: require('./nmma.png'),
  contact: require('./contact.png'),
  anniversary: require('./anniversary.png'),
  call: require('./call.png'),
  message: require('./message.png'),
  mail: require('./mail.png'),
  pencil: require('./pencil.png'),
  trash: require('./trash.png'),
  addmember: require('./addmember.png'),
  structure: require('./structure.png'),
  arrowForward: require('./arrow-forward.png'),
  me: require('./me.png'),
  editPencil: require('./editPencil.png'),
  arrowLeft: require('./arrowLeft.png'),
  info: require('./info.png'),
  family: require('./family.png'),
  favourite: require('./favourite.png'),
  hobby: require('./hobby.png'),
  burgerMenu: require('./burgerMenu.png'),
  chat: require('./chat.png'),

};

export default images;
